### ISSUE TITLE
how can I start the project, see it in my localhost?

### ISSUE THREAD

**Issue by willwinworld** [tameemsafi/react-js-learning-projects#1]
sorry, I am new to reactjs, I was wondering how can I start the imdb project, and see the project in my localhost? I type npm install, npm start, but error occured,npm ERR! missing script: start

**Comment by willwinworld** [comment]
Can you please help me? Also I am using gulp, http-server try to see the website on my localhost, still can't see...

**Comment by tameemsafi** [comment]
Each folder has its own package.json file. You will need to run npm install inside of each folder.

Also if you want to learn react, please see the link below:
https://egghead.io/courses/start-learning-react

This repo was just for testing.

**Comment by willwinworld** [comment]
I solved this problem, take imdb-movie-finder for instance, type gulp in command, and then visited dist folder index.html using local path, then I can see the website...thanks anyway!
